server:
  port: 9100
spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:mysql://mysqqqqql01:3306/seata_storage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: nacos.zing.com
        namespace: 332cee00-5754-4138-8166-f2b562bec976
    alibaba:
      seata:
        tx-service-group: storage-service-group
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysqqqqql01:3306/seata_storage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysqqqqql02:3306/seata_storage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
    sharding:
      master-slave-rules:
        master0:
          master-data-source-name: master
          slave-data-source-names:
            - slave
      tables:
        t_storage:
          actual-data-nodes: master0.t_storage${0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: t_storage${id % 2}
    props:
      sql.show: true
seata:
  tx-service-group: storage-service-group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: nacos.zing.com
      group: SEATA_GROUP
      namespace: 332cee00-5754-4138-8166-f2b562bec976
      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: nacos.zing.com
      group: SEATA_GROUP
      namespace: 332cee00-5754-4138-8166-f2b562bec976

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
