server:
  port: 10005

spring:
  application:
    name: test-web

dubbo:
  scan:
    base-packages: com.zing.test.api
  registry:
    protocol: zookeeper
    address: zookeeper:2181
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
