server:
  port: 10004

spring:
  application:
    name: test-redis
  redis:
    host: redis.zing
    port: 6379
    redisson:
      config: classpath:redisson-single-dev.yml

redisson:
  address: redis://redis.zing:6379

delay:
  task:
    redis:
      enabled: true

# xxl-job配置
xxl:
  job:
    admin:
      # 调度中心部署地址，如调度中心集群部署存在多个地址则用逗号分隔
      addresses: http://xxl-job-admin:8080/xxl-job-admin
    executor:
      # 执行器AppName
      appname: test-redis
      logretentiondays: 30
