server:
  port: 8081

spring:
  application:
    name: example

dubbo:
  scan:
    base-packages: com.zing.test.demo
  registry:
    protocol: zookeeper
    address: zookeeper:2181
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false

# xxl-job配置
xxl:
  job:
    admin:
      # 调度中心部署地址，如调度中心集群部署存在多个地址则用逗号分隔
      addresses: http://xxl-job-admin:8080/xxl-job-admin
    executor:
      # 执行器AppName
      appname: example
      logretentiondays: 30
